# Generated by Django 2.2.16 on 2025-02-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_id',
        ),
    ]
