# Generated by Django 2.2.16 on 2025-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_auto_20250205_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
    ]
