# Generated by Django 2.2.16 on 2025-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_auto_20250204_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='statut',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(default='poste', max_length=100),
        ),
    ]
