# Generated by Django 2.2.16 on 2025-02-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_auto_20250205_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
