# Generated by Django 2.2.16 on 2025-02-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_auto_20250211_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20),
        ),
    ]
