# Generated by Django 2.2.16 on 2025-02-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0007_auto_20250211_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
