# Generated by Django 2.2.16 on 2025-02-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0008_leaverequest_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved',
        ),
    ]
