# Generated by Django 2.2.16 on 2025-02-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('leave_app', '0009_remove_leaverequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewflow.Process'),
        ),
    ]
