# Generated by Django 2.2.16 on 2025-02-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0010_auto_20250212_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='status',
            new_name='request_status',
        ),
    ]
