# Generated by Django 2.2.16 on 2025-02-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('leave_app', '0011_auto_20250212_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('is_manager_approved', models.BooleanField(default=False, help_text='Validation de la demande de congé par le manager', verbose_name=' Approbatin par le Manager')),
                ('is_director_approved', models.BooleanField(default=False, help_text='Validation de la demande de congé par le directeur', verbose_name='Approbation par le Directeur')),
                ('is_finalized', models.BooleanField(default=False, help_text='Finalisation de la demande de congé', verbose_name='Terminé')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by_director',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by_manager',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='process',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_app.LeaveRequestProcess'),
        ),
        migrations.AddField(
            model_name='leaverequestprocess',
            name='leave_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_process', to='leave_app.LeaveRequest'),
        ),
    ]
