# Generated by Django 2.2.16 on 2025-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0012_auto_20250212_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequestprocess',
            name='is_manager_approved',
            field=models.BooleanField(default=False, help_text='Validation de la demande de congé par le manager', verbose_name=' Approbation par le Manager'),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
